### ISSUE TITLE
Is this folder location correct or bug ?

### ISSUE THREAD

**Issue by Nokia808** [flathub/br.gov.cti.invesalius#2]
Hi. I noticed that there is a folder belong to your application that I installed on my system as flatpak from FlatHub, this folder NOT located within /home/myusername/.var ! But instead it's path is:

/home/myusername/.invesalius

Is this normal or a bug ? For my knowledge (please correct to me if wrong) I know that flatpak application data & cache should located within /home/myusername/.var

**Comment by TingPing** [comment]
Its correct in that Invesalius uses that dir. Its incorrect in that upstream Invesalius should respect the XDG spec.

**Comment by tfmoraes** [comment]
Hi @Nokia808. This folder was created by an old version of InVesalius. The last one respect XDG spec. You may remove ~/.invesalius. The last version will put the config files inside ~/.var/app/br.gov.cti.invesalius/config/invesalius/config.json

**Comment by Nokia808** [comment]
Issue NOT resolved by newest version in FlatHub ! I tried to delete this folder & the folder that called:
/home/myusername/.var/app/br.gov.cti.invesalius
all together, then launch application again. But after launch program, this folder ~/.invesalius recreated again !
Version on my system is 3.1.99994

**Comment by tfmoraes** [comment]
Ok, it's a vestige of old versions. Fixed in InVesalius. I'll create a new flatpak version with this fix patched. Thanks!

**Comment by Nokia808** [comment]
It works. Thank you !
