### ISSUE TITLE
Version number in-correct !

### ISSUE THREAD

**Issue by Nokia808** [flathub/br.gov.cti.invesalius#3]
Hi. I updated to last version. Before update & after update, version number is 3.1.99994 but version number shown in both GNOME software centre & FlatHub is 3.1.99993 ! See the following:

https://www.flathub.org/apps/details/br.gov.cti.invesalius

What is this ? Where is wrong ? In FlatHub or in package ?

**Comment by tfmoraes** [comment]
I forgot to update the AppStream file. It's a error in the package.
